### ISSUE TITLE
Technical Story 5

### ISSUE THREAD

**Issue by Aleksandergreg** [KarlSixten/AlphaManagement#51]
## Styling ##

**Create HTML and CSS styling for all html pages, using bootstrap and dynamics**

### Tasks: 

- [x] Style create_emp.html
- [x] Style createProject.html
- [x] Style find_user.html
- [x] Style front-page.html
- [x] Style login.html
- [x] Style projectView.html
- [x] Style update-emp.html
- [x] Style update-project.html
- [x] Style user_created_success.html
